# Dependabot configuration for automated dependency updates
# This configuration monitors various package ecosystems for updates

version: 2
updates:
  # Monitor GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "@ravichillerega"
    assignees:
      - "@ravichillerega"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "security"

  # Monitor Docker base images (though limited support for Containerfiles)
  - package-ecosystem: "docker"
    directory: "/os"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
    open-pull-requests-limit: 3
    reviewers:
      - "@ravichillerega"
    assignees:
      - "@ravichillerega"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "security"
      - "container-image"

  # Note: golang ecosystem is not monitored because:
  # - MicroShift is built from external repository source
  # - golang dependencies are managed upstream in MicroShift repo
  # - No go.mod/go.sum files exist in this repository

  # Monitor npm dependencies if any Node.js components are added
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "06:00"
    open-pull-requests-limit: 3
    reviewers:
      - "@ravichillerega"
    assignees:
      - "@ravichillerega"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
      - "javascript" 