# Trivy Configuration for os-builder repository
# Centralized configuration to ensure consistency across all workflows
# Fixed to handle AWS policy parsing errors

# General settings
format: table
exit-code: 1
quiet: false

# Scanner configuration - Only essential scanners (NO cloud policy scanning)
scanners:
  - vuln      # Vulnerability scanning
  - secret    # Secret detection
  # misconfig scanner disabled - causes cloud policy issues

# Misconfiguration scanning completely disabled
# No misconfig-scanners needed
# No policy exclusions needed since misconfig is disabled

# Severity levels to scan for (can be overridden by workflow inputs)
severity:
  - CRITICAL
  - HIGH
  - MEDIUM

# Standardized skip directories for all scan types
# These directories are commonly excluded across all workflows
skip-dirs:
  - .git/
  - .github/
  - node_modules/
  - .vscode/
  - .idea/
  - dist/
  - build/
  - target/
  - vendor/
  - /var/cache
  - /var/log/dnf*
  - /var/lib/dnf
  - /tmp

# Skip files that don't need scanning
skip-files:
  - "*.md"
  - "*.txt"
  - "*.log"
  - "*.tar.gz"
  - "*.tar.xz"
  - "*.tar.zst"
  - "*.zip"
  - "*.rpm"
  - "*.deb"
  - "LICENSE*"
  - "NOTICE*"
  - "CHANGELOG*"
  - "*.cache"

# Vulnerability scanning settings
vuln:
  type:
    - os
    - library

# Secret scanning settings
secret:
  skip-dirs:
    - .git/
    - .github/actions/
  skip-files:
    - "*.md"
    - "*.example"
    - "*.template"

# Output configuration
output:
  clean: true
  
# Ignore unfixed vulnerabilities for better signal-to-noise ratio
ignore-unfixed: true

# Performance settings
timeout: 10m

# Cache settings
cache:
  cache-dir: ~/.cache/trivy 