# This collector runs on the host OS and forwards telemetry to the K3s cluster
receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
      disk:
      filesystem:
      load:
      memory:
      network:
      paging:
      processes:

  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['0.0.0.0:8888']
        - job_name: 'node-exporter'
          scrape_interval: 15s
          static_configs:
            - targets: ['localhost:9100']
        - job_name: 'k3s'
          scrape_interval: 30s
          static_configs:
            - targets: ['localhost:10250']
          metrics_path: '/metrics'
        - job_name: 'k3s-cadvisor'
          scrape_interval: 30s
          static_configs:
            - targets: ['localhost:10250']
          metrics_path: '/metrics/cadvisor'

processors:
  batch:
    timeout: 5s
    send_batch_size: 256

  resource:
    attributes:
      - key: service.name
        value: "edge-device"
        action: insert
      - key: service.version
        value: "1.0.0"
        action: insert
      - key: host.name
        from_attribute: host.name
        action: upsert

  resourcedetection:
    detectors: [env, system]
    timeout: 2s
    override: false

  memory_limiter:
    limit_mib: 256

exporters:
  # Local debugging
  logging:
    loglevel: info

  # Export to OpenTelemetry Collector in K3s cluster
  otlp/k3s:
    endpoint: "http://localhost:4317"
    tls:
      insecure: true

  # Export to external OTLP endpoint (if configured)
  otlp/external:
    endpoint: "${OTEL_EXPORTER_OTLP_ENDPOINT}"
    headers:
      authorization: "Bearer ${OTEL_EXPORTER_OTLP_HEADERS_AUTHORIZATION}"
    tls:
      insecure: true

service:
  telemetry:
    logs:
      level: "info"
    metrics:
      address: 0.0.0.0:8888

  pipelines:
    metrics:
      receivers: [hostmetrics, prometheus]
      processors: [memory_limiter, resourcedetection, resource, batch]
      exporters: [logging, otlp/k3s]

    traces:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, resource, batch]
      exporters: [logging, otlp/k3s]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection, resource, batch]
      exporters: [logging, otlp/k3s] 