# MicroShift Configuration
apiServer:
  auditLog:
    maxFileAge: 7
    maxFileSize: 200
    maxFiles: 5
    profile: Default
  subjectAltNames:
  - microshift.local
etcd:
  memoryLimitMB: 128
network:
  clusterNetwork:
  - 10.42.0.0/16
  serviceNetwork:
  - 10.43.0.0/16
  serviceNodePortRange: "30000-32767"
node:
  hostnameOverride: ""
  nodeIP: ""
ingress:
  listenAddress:
  - 0.0.0.0
  routeAdmissionPolicy:
    namespaceOwnership: InterNamespaceAllowed 