# bootc-image-builder configuration
# Custom kickstart.ks content will be automatically embedded by the build action
# This file serves as the base configuration - kickstart content is added dynamically 