# This workflow is deprecated. Please use build-and-security-scan.yaml instead
name: Legacy OS Container Build (Deprecated)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'This workflow is deprecated. Type "confirm" to run anyway.'
        required: true
        default: 'use-build-and-security-scan-instead'

jobs:
  deprecation-notice:
    runs-on: ubuntu-latest
    steps:
      - name: Deprecation Notice
        run: |
          echo "::warning::This workflow is deprecated. Please use 'build-and-security-scan.yaml' instead."
          echo "The new workflow provides:"
          echo "- Comprehensive security scanning with Trivy"
          echo "- SARIF upload to GitHub Advanced Security"
          echo "- Multi-platform builds"
          echo "- SBOM generation"
          echo "- Better error handling and caching"
          echo ""
          echo "To trigger the new workflow, go to Actions > Build and Security Scan"
          
          if [ "${{ github.event.inputs.confirm }}" != "confirm" ]; then
            echo "::error::Workflow not confirmed. Please use the new workflow instead."
            exit 1
          fi
          